# Generated by Django 3.2.8 on 2021-10-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Division',
        ),
    ]
